### ISSUE TITLE
Auto-convert to headings/lists when special symbol and space is typed

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-rich-editors#6]
When user types the special symbol(#, ##, ##, +, - , *) at start of the line (or only preceding by white spaces) and enters the white space after the symbol, then the line should be formatted with corresponding style.
![see current displaying](https://user-images.githubusercontent.com/25081403/27335490-3c9fc586-55d5-11e7-9f94-06b826bd432c.png)

**Comment by asergeev-sc** [comment]
It looks like you need Markdown editor, here we have rich editors only (no markup in the editor).
